### ISSUE TITLE
Quit button

### ISSUE THREAD

**Issue by zakharchenkoAndrii** [masich/SaveMyEyes#1]
Hi, there is an issue with the quit button.

![Screenshot](https://user-images.githubusercontent.com/14369863/76650158-ae187a80-656a-11ea-9f0a-a82a21bc9ab3.png)

**Comment by Wiorik** [comment]
![image](https://user-images.githubusercontent.com/23197387/76650031-7a3d5500-656a-11ea-87eb-cfa6dfac7157.png)

**Comment by masich** [comment]
@Wiorik do you use the latest available macOS version? Please, install updates, if any.

**Comment by zakharchenkoAndrii** [comment]
Thanks! It works!
